---
- name: Install Neutron
  hosts: controller
  become: true
  tasks:
    - name: Install Neutron Packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - neutron-server
        - neutron-plugin-ml2
